package com.xs.dzyxh.entity.driver;
// Generated 2016-11-7 14:29:22 by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * TmDrivingBase generated by hbm2java 基本信息表
 */
@Entity
@Table(name = "TM_DRIVING_BASE", schema = "ARC_DRIVER")
public class DrivingBase implements java.io.Serializable {

	private String sfzmhm;// 身份证明号码
	private char sfzmmc;// 身份证明名称
	private Character hmcd;// 号码长度标志
	private String xm;// 姓名
	private String xb;// 性别
	private Date csrq;// 出生日期
	private String gj;// 国籍
	private String djzsxzqh;// 登记住所行政区划
	private String djzsxxdz;// 登记住所详细地址
	private String lxzsxzqh;// 联系住所行政区划
	private String lxzsxxdz;// 联系住所详细地址
	private String lxzsyzbm;// 邮政编码
	private String lxdh;// 联系电话
	private String zzzm;// 暂住证明
	private Date gxsj;// 更新时间
	private Character sfbd;// 是否本地,1本地0外地
	private String sjhm;// 手机号码
	private String dzyx;// 电子邮箱
	private Character csbj;// 电子邮箱
	private String qh;// 期号
	private String jxdm;// 驾校代码,代码表外键
	private Date cjsj;// 创建时间
	private Date cjsjks;
	private Date cjsjjs;
	/*private Date kssj;
	private Date jssj;*/
	public DrivingBase() {
	}

	public DrivingBase(String sfzmhm, char sfzmmc) {
		this.sfzmhm = sfzmhm;
		this.sfzmmc = sfzmmc;
	}

	public DrivingBase(String sfzmhm, char sfzmmc, Character hmcd, String xm, String xb, Date csrq, String gj,
			String djzsxzqh, String djzsxxdz, String lxzsxzqh, String lxzsxxdz, String lxzsyzbm, String lxdh,
			String zzzm, Date gxsj, Character sfbd, String sjhm, String dzyx, Character csbj, String qh,String jxdm,Date cjsj) {
		this.sfzmhm = sfzmhm;
		this.sfzmmc = sfzmmc;
		this.hmcd = hmcd;
		this.xm = xm;
		this.xb = xb;
		this.csrq = csrq;
		this.gj = gj;
		this.djzsxzqh = djzsxzqh;
		this.djzsxxdz = djzsxxdz;
		this.lxzsxzqh = lxzsxzqh;
		this.lxzsxxdz = lxzsxxdz;
		this.lxzsyzbm = lxzsyzbm;
		this.lxdh = lxdh;
		this.zzzm = zzzm;
		this.gxsj = gxsj;
		this.sfbd = sfbd;
		this.sjhm = sjhm;
		this.dzyx = dzyx;
		this.csbj = csbj;
		this.qh = qh;
		this.jxdm = jxdm;
		this.cjsj = cjsj;
	}

	@Id

	@Column(name = "SFZMHM", unique = true, nullable = false, length = 32)
	public String getSfzmhm() {
		return this.sfzmhm;
	}

	public void setSfzmhm(String sfzmhm) {
		this.sfzmhm = sfzmhm;
	}

	@Column(name = "SFZMMC",  length = 1)
	public char getSfzmmc() {
		return this.sfzmmc;
	}

	public void setSfzmmc(char sfzmmc) {
		this.sfzmmc = sfzmmc;
	}

	@Column(name = "HMCD", length = 1)
	public Character getHmcd() {
		if(this.hmcd==null){
			return new Character(' ');
		}
		return this.hmcd;
	}

	public void setHmcd(Character hmcd) {
		this.hmcd = hmcd;
	}

	@Column(name = "XM", length = 30)
	public String getXm() {
		if(xm==null){
			return "";
		}
		return this.xm;
	}

	public void setXm(String xm) {
		this.xm = xm;
	}

	@Column(name = "XB", length = 20)
	public String getXb() {
		if(xb==null){
			return "";
		}
		return this.xb;
	}

	public void setXb(String xb) {
		this.xb = xb;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CSRQ", length = 7)
	public Date getCsrq() {
		return this.csrq;
	}

	public void setCsrq(Date csrq) {
		this.csrq = csrq;
	}

	@Column(name = "GJ", length = 20)
	public String getGj() {
		if(gj==null){
			return "";
		}
		return this.gj;
	}

	public void setGj(String gj) {
		this.gj = gj;
	}

	@Column(name = "DJZSXZQH", length = 10)
	public String getDjzsxzqh() {
		if(this.djzsxzqh==null){
			return "";
		}
		return this.djzsxzqh;
	}

	public void setDjzsxzqh(String djzsxzqh) {
		this.djzsxzqh = djzsxzqh;
	}

	@Column(name = "DJZSXXDZ", length = 128)
	public String getDjzsxxdz() {
		if(this.djzsxxdz==null){
			return "";
		}
		return this.djzsxxdz;
	}

	public void setDjzsxxdz(String djzsxxdz) {
		this.djzsxxdz = djzsxxdz;
	}

	@Column(name = "LXZSXZQH", length = 10)
	public String getLxzsxzqh() {
		if(this.lxzsxzqh==null){
			return "";
		}
		return this.lxzsxzqh;
	}

	public void setLxzsxzqh(String lxzsxzqh) {
		this.lxzsxzqh = lxzsxzqh;
	}

	@Column(name = "LXZSXXDZ", length = 128)
	public String getLxzsxxdz() {
		if(this.lxzsxxdz==null){
			return "";
		}
		return this.lxzsxxdz;
	}

	public void setLxzsxxdz(String lxzsxxdz) {
		this.lxzsxxdz = lxzsxxdz;
	}

	@Column(name = "LXZSYZBM", length = 6)
	public String getLxzsyzbm() {
		if(this.lxzsyzbm==null){
			return "";
		}
		return this.lxzsyzbm;
	}

	public void setLxzsyzbm(String lxzsyzbm) {
		this.lxzsyzbm = lxzsyzbm;
	}

	@Column(name = "LXDH", length = 20)
	public String getLxdh() {
		if(this.lxdh==null){
			return "";
		}
		return this.lxdh;
	}

	public void setLxdh(String lxdh) {
		this.lxdh = lxdh;
	}

	@Column(name = "ZZZM", length = 32)
	public String getZzzm() {
		if(this.zzzm==null){
			return "";
		}
		return this.zzzm;
	}

	public void setZzzm(String zzzm) {
		this.zzzm = zzzm;
	}
	@JsonFormat(pattern = "yyyy-MM-dd")
	@DateTimeFormat( pattern = "yyyy-MM-dd HH:mm:ss" )
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "GXSJ", length = 7)
	public Date getGxsj() {
		return this.gxsj;
	}

	public void setGxsj(Date gxsj) {
		this.gxsj = gxsj;
	}

	@Column(name = "SFBD", length = 1)
	public Character getSfbd() {
		if(this.sfbd==null){
			return new Character(' ');
		}
		return this.sfbd;
	}

	public void setSfbd(Character sfbd) {
		this.sfbd = sfbd;
	}

	@Column(name = "SJHM", length = 20)
	public String getSjhm() {
		if(this.sjhm==null){
			return "";
		}
		return this.sjhm;
	}

	public void setSjhm(String sjhm) {
		this.sjhm = sjhm;
	}

	@Column(name = "DZYX")
	public String getDzyx() {
		if(this.dzyx==null){
			return "";
		}
		return this.dzyx;
	}

	public void setDzyx(String dzyx) {
		this.dzyx = dzyx;
	}

	@Column(name = "CSBJ", length = 1)
	public Character getCsbj() {
		if(this.csbj==null){
			return new Character(' ');
		}
		return this.csbj;
	}

	public void setCsbj(Character csbj) {
		this.csbj = csbj;
	}

	@Column(name = "QH", length = 10, nullable = false)
	public String getQh() {
		if(qh==null){
			return "";
		}
		return qh;
	}

	public void setQh(String qh) {
		this.qh = qh;
	}

	@Column(name = "JXDM", length = 2, nullable = false)
	public String getJxdm() {
		if(jxdm==null){
			return "";
		}
		return jxdm;
	}

	public void setJxdm(String jxdm) {
		this.jxdm = jxdm;
	}
	
	@JsonFormat(pattern = "yyyy-MM-dd")
	@DateTimeFormat( pattern = "yyyy-MM-dd HH:mm:ss" )
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CJSJ", length = 7)
	public Date getCjsj() {
		return this.cjsj;
	}

	public void setCjsj(Date cjsj) {
		this.cjsj = cjsj;
	}
	@JsonFormat(pattern = "yyyy-MM-dd")
	@DateTimeFormat( pattern = "yyyy-MM-dd" )
	@Transient
	public Date getCjsjks() {
		return cjsjks;
	}

	public void setCjsjks(Date cjsjks) {
		this.cjsjks = cjsjks;
	}
	@JsonFormat(pattern = "yyyy-MM-dd")
	@DateTimeFormat( pattern = "yyyy-MM-dd" )
	@Transient
	public Date getCjsjjs() {
		return cjsjjs;
	}

	public void setCjsjjs(Date cjsjjs) {
		this.cjsjjs = cjsjjs;
	}

/*	public Date getKssj() {
		return kssj;
	}

	public void setKssj(Date kssj) {
		this.kssj = kssj;
	}

	public Date getJssj() {
		return jssj;
	}

	public void setJssj(Date jssj) {
		this.jssj = jssj;
	}*/
	
}
