package com.xs.dzyxh.entity.driver;
// Generated 2016-11-7 14:29:22 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmDrivingBase generated by hbm2java
 */
@Entity
@Table(name = "TM_DRIVING_BASE", schema = "ARC_DRIVER")
public class DrivingBase implements java.io.Serializable {

	private String sfzmhm;
	private char sfzmmc;
	private Character hmcd;
	private String xm;
	private String xb;
	private Date csrq;
	private String gj;
	private String djzsxzqh;
	private String djzsxxdz;
	private String lxzsxzqh;
	private String lxzsxxdz;
	private String lxzsyzbm;
	private String lxdh;
	private String zzzm;
	private Date gxsj;
	private Character sfbd;
	private String sjhm;
	private String dzyx;
	private Character csbj;

	public DrivingBase() {
	}

	public DrivingBase(String sfzmhm, char sfzmmc) {
		this.sfzmhm = sfzmhm;
		this.sfzmmc = sfzmmc;
	}

	public DrivingBase(String sfzmhm, char sfzmmc, Character hmcd, String xm, String xb, Date csrq, String gj,
			String djzsxzqh, String djzsxxdz, String lxzsxzqh, String lxzsxxdz, String lxzsyzbm, String lxdh,
			String zzzm, Date gxsj, Character sfbd, String sjhm, String dzyx, Character csbj) {
		this.sfzmhm = sfzmhm;
		this.sfzmmc = sfzmmc;
		this.hmcd = hmcd;
		this.xm = xm;
		this.xb = xb;
		this.csrq = csrq;
		this.gj = gj;
		this.djzsxzqh = djzsxzqh;
		this.djzsxxdz = djzsxxdz;
		this.lxzsxzqh = lxzsxzqh;
		this.lxzsxxdz = lxzsxxdz;
		this.lxzsyzbm = lxzsyzbm;
		this.lxdh = lxdh;
		this.zzzm = zzzm;
		this.gxsj = gxsj;
		this.sfbd = sfbd;
		this.sjhm = sjhm;
		this.dzyx = dzyx;
		this.csbj = csbj;
	}

	@Id

	@Column(name = "SFZMHM", unique = true, nullable = false, length = 32)
	public String getSfzmhm() {
		return this.sfzmhm;
	}

	public void setSfzmhm(String sfzmhm) {
		this.sfzmhm = sfzmhm;
	}

	@Column(name = "SFZMMC", nullable = false, length = 1)
	public char getSfzmmc() {
		return this.sfzmmc;
	}

	public void setSfzmmc(char sfzmmc) {
		this.sfzmmc = sfzmmc;
	}

	@Column(name = "HMCD", length = 1)
	public Character getHmcd() {
		return this.hmcd;
	}

	public void setHmcd(Character hmcd) {
		this.hmcd = hmcd;
	}

	@Column(name = "XM", length = 30)
	public String getXm() {
		return this.xm;
	}

	public void setXm(String xm) {
		this.xm = xm;
	}

	@Column(name = "XB", length = 20)
	public String getXb() {
		return this.xb;
	}

	public void setXb(String xb) {
		this.xb = xb;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CSRQ", length = 7)
	public Date getCsrq() {
		return this.csrq;
	}

	public void setCsrq(Date csrq) {
		this.csrq = csrq;
	}

	@Column(name = "GJ", length = 20)
	public String getGj() {
		return this.gj;
	}

	public void setGj(String gj) {
		this.gj = gj;
	}

	@Column(name = "DJZSXZQH", length = 10)
	public String getDjzsxzqh() {
		return this.djzsxzqh;
	}

	public void setDjzsxzqh(String djzsxzqh) {
		this.djzsxzqh = djzsxzqh;
	}

	@Column(name = "DJZSXXDZ", length = 128)
	public String getDjzsxxdz() {
		return this.djzsxxdz;
	}

	public void setDjzsxxdz(String djzsxxdz) {
		this.djzsxxdz = djzsxxdz;
	}

	@Column(name = "LXZSXZQH", length = 10)
	public String getLxzsxzqh() {
		return this.lxzsxzqh;
	}

	public void setLxzsxzqh(String lxzsxzqh) {
		this.lxzsxzqh = lxzsxzqh;
	}

	@Column(name = "LXZSXXDZ", length = 128)
	public String getLxzsxxdz() {
		return this.lxzsxxdz;
	}

	public void setLxzsxxdz(String lxzsxxdz) {
		this.lxzsxxdz = lxzsxxdz;
	}

	@Column(name = "LXZSYZBM", length = 6)
	public String getLxzsyzbm() {
		return this.lxzsyzbm;
	}

	public void setLxzsyzbm(String lxzsyzbm) {
		this.lxzsyzbm = lxzsyzbm;
	}

	@Column(name = "LXDH", length = 20)
	public String getLxdh() {
		return this.lxdh;
	}

	public void setLxdh(String lxdh) {
		this.lxdh = lxdh;
	}

	@Column(name = "ZZZM", length = 32)
	public String getZzzm() {
		return this.zzzm;
	}

	public void setZzzm(String zzzm) {
		this.zzzm = zzzm;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "GXSJ", length = 7)
	public Date getGxsj() {
		return this.gxsj;
	}

	public void setGxsj(Date gxsj) {
		this.gxsj = gxsj;
	}

	@Column(name = "SFBD", length = 1)
	public Character getSfbd() {
		return this.sfbd;
	}

	public void setSfbd(Character sfbd) {
		this.sfbd = sfbd;
	}

	@Column(name = "SJHM", length = 20)
	public String getSjhm() {
		return this.sjhm;
	}

	public void setSjhm(String sjhm) {
		this.sjhm = sjhm;
	}

	@Column(name = "DZYX")
	public String getDzyx() {
		return this.dzyx;
	}

	public void setDzyx(String dzyx) {
		this.dzyx = dzyx;
	}

	@Column(name = "CSBJ", length = 1)
	public Character getCsbj() {
		return this.csbj;
	}

	public void setCsbj(Character csbj) {
		this.csbj = csbj;
	}

}
