package com.xs.dzyxh.entity.driver;
// Generated 2016-11-7 14:29:22 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TmDrivingExaminationId generated by hbm2java
 */
@Embeddable
public class DrivingExaminationId implements java.io.Serializable {

	private String qh;
	private String sfzmhm;
	private String jxdm;

	public DrivingExaminationId() {
	}

	public DrivingExaminationId(String qh, String sfzmhm, String jxdm) {
		this.qh = qh;
		this.sfzmhm = sfzmhm;
		this.jxdm = jxdm;
	}

	@Column(name = "QH", nullable = false, length = 10)
	public String getQh() {
		return this.qh;
	}

	public void setQh(String qh) {
		this.qh = qh;
	}

	@Column(name = "SFZMHM", nullable = false, length = 20)
	public String getSfzmhm() {
		return this.sfzmhm;
	}

	public void setSfzmhm(String sfzmhm) {
		this.sfzmhm = sfzmhm;
	}

	@Column(name = "JXDM", nullable = false, length = 2)
	public String getJxdm() {
		return this.jxdm;
	}

	public void setJxdm(String jxdm) {
		this.jxdm = jxdm;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DrivingExaminationId))
			return false;
		DrivingExaminationId castOther = (DrivingExaminationId) other;

		return ((this.getQh() == castOther.getQh())
				|| (this.getQh() != null && castOther.getQh() != null && this.getQh().equals(castOther.getQh())))
				&& ((this.getSfzmhm() == castOther.getSfzmhm()) || (this.getSfzmhm() != null
						&& castOther.getSfzmhm() != null && this.getSfzmhm().equals(castOther.getSfzmhm())))
				&& ((this.getJxdm() == castOther.getJxdm()) || (this.getJxdm() != null && castOther.getJxdm() != null
						&& this.getJxdm().equals(castOther.getJxdm())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getQh() == null ? 0 : this.getQh().hashCode());
		result = 37 * result + (getSfzmhm() == null ? 0 : this.getSfzmhm().hashCode());
		result = 37 * result + (getJxdm() == null ? 0 : this.getJxdm().hashCode());
		return result;
	}

}
