package com.xs.dzyxh.entity.driver;
// Generated 2016-11-7 14:29:22 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmDrivingApply generated by hbm2java
 */
@Entity
@Table(name = "TM_DRIVING_APPLY", schema = "ARC_DRIVER")
public class DrivingApply implements java.io.Serializable {

	private DrivingApplyId id;
	private String lsh;
	private Character ly;
	private String xzqh;
	private String zzzm;
	private String dabh;
	private Short sg;
	private BigDecimal zsl;
	private BigDecimal ysl;
	private Character bsl;
	private Character tl;
	private Character sz;
	private Character zxz;
	private Character yxz;
	private Character qgjb;
	private Date tjrq;
	private String tjyymc;
	private String by1;
	private String by2;
	private Character bj1;
	private Character bj2;
	private Character dyslze;
	private BigDecimal yyspsy;
	private String wwlsh;
	private String yjdz;
	private String ywlx;
	private String sqzjcxdh;
	private String scjszzl;
	private String bgsx;
	private String bgnr;
	private String cydw;
	private String sqyq;
	private String sqfs;
	private String wtjhrxm;
	private String wtjhrsfzmc;
	private String wtjhrsfzmhm;
	private String wtjhrlxdz;
	private String wtjhrlxdh;
	private String sqrqzzp;
	private Date sqrq;
	private String dlrqzzp;
	private String jxmc;
	private Date cjsj;
	private Date gxsj;
	private String cjyh;
	private String gxyh;
	private String zkzmbh;
	private Character csbj;

	public DrivingApply() {
	}

	public DrivingApply(DrivingApplyId id) {
		this.id = id;
	}

	public DrivingApply(DrivingApplyId id, String lsh, Character ly, String xzqh, String zzzm, String dabh,
			Short sg, BigDecimal zsl, BigDecimal ysl, Character bsl, Character tl, Character sz, Character zxz,
			Character yxz, Character qgjb, Date tjrq, String tjyymc, String by1, String by2, Character bj1,
			Character bj2, Character dyslze, BigDecimal yyspsy, String wwlsh, String yjdz, String ywlx, String sqzjcxdh,
			String scjszzl, String bgsx, String bgnr, String cydw, String sqyq, String sqfs, String wtjhrxm,
			String wtjhrsfzmc, String wtjhrsfzmhm, String wtjhrlxdz, String wtjhrlxdh, String sqrqzzp, Date sqrq,
			String dlrqzzp, String jxmc, Date cjsj, Date gxsj, String cjyh, String gxyh, String zkzmbh,
			Character csbj) {
		this.id = id;
		this.lsh = lsh;
		this.ly = ly;
		this.xzqh = xzqh;
		this.zzzm = zzzm;
		this.dabh = dabh;
		this.sg = sg;
		this.zsl = zsl;
		this.ysl = ysl;
		this.bsl = bsl;
		this.tl = tl;
		this.sz = sz;
		this.zxz = zxz;
		this.yxz = yxz;
		this.qgjb = qgjb;
		this.tjrq = tjrq;
		this.tjyymc = tjyymc;
		this.by1 = by1;
		this.by2 = by2;
		this.bj1 = bj1;
		this.bj2 = bj2;
		this.dyslze = dyslze;
		this.yyspsy = yyspsy;
		this.wwlsh = wwlsh;
		this.yjdz = yjdz;
		this.ywlx = ywlx;
		this.sqzjcxdh = sqzjcxdh;
		this.scjszzl = scjszzl;
		this.bgsx = bgsx;
		this.bgnr = bgnr;
		this.cydw = cydw;
		this.sqyq = sqyq;
		this.sqfs = sqfs;
		this.wtjhrxm = wtjhrxm;
		this.wtjhrsfzmc = wtjhrsfzmc;
		this.wtjhrsfzmhm = wtjhrsfzmhm;
		this.wtjhrlxdz = wtjhrlxdz;
		this.wtjhrlxdh = wtjhrlxdh;
		this.sqrqzzp = sqrqzzp;
		this.sqrq = sqrq;
		this.dlrqzzp = dlrqzzp;
		this.jxmc = jxmc;
		this.cjsj = cjsj;
		this.gxsj = gxsj;
		this.cjyh = cjyh;
		this.gxyh = gxyh;
		this.zkzmbh = zkzmbh;
		this.csbj = csbj;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "jxdm", column = @Column(name = "JXDM", nullable = false, length = 2)),
			@AttributeOverride(name = "qh", column = @Column(name = "QH", nullable = false, length = 10)),
			@AttributeOverride(name = "sfzmhm", column = @Column(name = "SFZMHM", nullable = false, length = 20)) })
	public DrivingApplyId getId() {
		return this.id;
	}

	public void setId(DrivingApplyId id) {
		this.id = id;
	}

	@Column(name = "LSH", length = 32)
	public String getLsh() {
		return this.lsh;
	}

	public void setLsh(String lsh) {
		this.lsh = lsh;
	}

	@Column(name = "LY", length = 1)
	public Character getLy() {
		return this.ly;
	}

	public void setLy(Character ly) {
		this.ly = ly;
	}

	@Column(name = "XZQH", length = 10)
	public String getXzqh() {
		return this.xzqh;
	}

	public void setXzqh(String xzqh) {
		this.xzqh = xzqh;
	}

	@Column(name = "ZZZM", length = 18)
	public String getZzzm() {
		return this.zzzm;
	}

	public void setZzzm(String zzzm) {
		this.zzzm = zzzm;
	}

	@Column(name = "DABH", length = 12)
	public String getDabh() {
		return this.dabh;
	}

	public void setDabh(String dabh) {
		this.dabh = dabh;
	}

	@Column(name = "SG", precision = 3, scale = 0)
	public Short getSg() {
		return this.sg;
	}

	public void setSg(Short sg) {
		this.sg = sg;
	}

	@Column(name = "ZSL", precision = 3, scale = 1)
	public BigDecimal getZsl() {
		return this.zsl;
	}

	public void setZsl(BigDecimal zsl) {
		this.zsl = zsl;
	}

	@Column(name = "YSL", precision = 3, scale = 1)
	public BigDecimal getYsl() {
		return this.ysl;
	}

	public void setYsl(BigDecimal ysl) {
		this.ysl = ysl;
	}

	@Column(name = "BSL", length = 1)
	public Character getBsl() {
		return this.bsl;
	}

	public void setBsl(Character bsl) {
		this.bsl = bsl;
	}

	@Column(name = "TL", length = 1)
	public Character getTl() {
		return this.tl;
	}

	public void setTl(Character tl) {
		this.tl = tl;
	}

	@Column(name = "SZ", length = 1)
	public Character getSz() {
		return this.sz;
	}

	public void setSz(Character sz) {
		this.sz = sz;
	}

	@Column(name = "ZXZ", length = 1)
	public Character getZxz() {
		return this.zxz;
	}

	public void setZxz(Character zxz) {
		this.zxz = zxz;
	}

	@Column(name = "YXZ", length = 1)
	public Character getYxz() {
		return this.yxz;
	}

	public void setYxz(Character yxz) {
		this.yxz = yxz;
	}

	@Column(name = "QGJB", length = 1)
	public Character getQgjb() {
		return this.qgjb;
	}

	public void setQgjb(Character qgjb) {
		this.qgjb = qgjb;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TJRQ", length = 7)
	public Date getTjrq() {
		return this.tjrq;
	}

	public void setTjrq(Date tjrq) {
		this.tjrq = tjrq;
	}

	@Column(name = "TJYYMC", length = 64)
	public String getTjyymc() {
		return this.tjyymc;
	}

	public void setTjyymc(String tjyymc) {
		this.tjyymc = tjyymc;
	}

	@Column(name = "BY1")
	public String getBy1() {
		return this.by1;
	}

	public void setBy1(String by1) {
		this.by1 = by1;
	}

	@Column(name = "BY2")
	public String getBy2() {
		return this.by2;
	}

	public void setBy2(String by2) {
		this.by2 = by2;
	}

	@Column(name = "BJ1", length = 1)
	public Character getBj1() {
		return this.bj1;
	}

	public void setBj1(Character bj1) {
		this.bj1 = bj1;
	}

	@Column(name = "BJ2", length = 1)
	public Character getBj2() {
		return this.bj2;
	}

	public void setBj2(Character bj2) {
		this.bj2 = bj2;
	}

	@Column(name = "DYSLZE", length = 1)
	public Character getDyslze() {
		return this.dyslze;
	}

	public void setDyslze(Character dyslze) {
		this.dyslze = dyslze;
	}

	@Column(name = "YYSPSY", precision = 3, scale = 1)
	public BigDecimal getYyspsy() {
		return this.yyspsy;
	}

	public void setYyspsy(BigDecimal yyspsy) {
		this.yyspsy = yyspsy;
	}

	@Column(name = "WWLSH")
	public String getWwlsh() {
		return this.wwlsh;
	}

	public void setWwlsh(String wwlsh) {
		this.wwlsh = wwlsh;
	}

	@Column(name = "YJDZ")
	public String getYjdz() {
		return this.yjdz;
	}

	public void setYjdz(String yjdz) {
		this.yjdz = yjdz;
	}

	@Column(name = "YWLX", length = 10)
	public String getYwlx() {
		return this.ywlx;
	}

	public void setYwlx(String ywlx) {
		this.ywlx = ywlx;
	}

	@Column(name = "SQZJCXDH", length = 10)
	public String getSqzjcxdh() {
		return this.sqzjcxdh;
	}

	public void setSqzjcxdh(String sqzjcxdh) {
		this.sqzjcxdh = sqzjcxdh;
	}

	@Column(name = "SCJSZZL", length = 10)
	public String getScjszzl() {
		return this.scjszzl;
	}

	public void setScjszzl(String scjszzl) {
		this.scjszzl = scjszzl;
	}

	@Column(name = "BGSX")
	public String getBgsx() {
		return this.bgsx;
	}

	public void setBgsx(String bgsx) {
		this.bgsx = bgsx;
	}

	@Column(name = "BGNR")
	public String getBgnr() {
		return this.bgnr;
	}

	public void setBgnr(String bgnr) {
		this.bgnr = bgnr;
	}

	@Column(name = "CYDW")
	public String getCydw() {
		return this.cydw;
	}

	public void setCydw(String cydw) {
		this.cydw = cydw;
	}

	@Column(name = "SQYQ", length = 10)
	public String getSqyq() {
		return this.sqyq;
	}

	public void setSqyq(String sqyq) {
		this.sqyq = sqyq;
	}

	@Column(name = "SQFS", length = 20)
	public String getSqfs() {
		return this.sqfs;
	}

	public void setSqfs(String sqfs) {
		this.sqfs = sqfs;
	}

	@Column(name = "WTJHRXM", length = 32)
	public String getWtjhrxm() {
		return this.wtjhrxm;
	}

	public void setWtjhrxm(String wtjhrxm) {
		this.wtjhrxm = wtjhrxm;
	}

	@Column(name = "WTJHRSFZMC", length = 10)
	public String getWtjhrsfzmc() {
		return this.wtjhrsfzmc;
	}

	public void setWtjhrsfzmc(String wtjhrsfzmc) {
		this.wtjhrsfzmc = wtjhrsfzmc;
	}

	@Column(name = "WTJHRSFZMHM", length = 20)
	public String getWtjhrsfzmhm() {
		return this.wtjhrsfzmhm;
	}

	public void setWtjhrsfzmhm(String wtjhrsfzmhm) {
		this.wtjhrsfzmhm = wtjhrsfzmhm;
	}

	@Column(name = "WTJHRLXDZ")
	public String getWtjhrlxdz() {
		return this.wtjhrlxdz;
	}

	public void setWtjhrlxdz(String wtjhrlxdz) {
		this.wtjhrlxdz = wtjhrlxdz;
	}

	@Column(name = "WTJHRLXDH", length = 20)
	public String getWtjhrlxdh() {
		return this.wtjhrlxdh;
	}

	public void setWtjhrlxdh(String wtjhrlxdh) {
		this.wtjhrlxdh = wtjhrlxdh;
	}

	@Column(name = "SQRQZZP", length = 32)
	public String getSqrqzzp() {
		return this.sqrqzzp;
	}

	public void setSqrqzzp(String sqrqzzp) {
		this.sqrqzzp = sqrqzzp;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SQRQ", length = 7)
	public Date getSqrq() {
		return this.sqrq;
	}

	public void setSqrq(Date sqrq) {
		this.sqrq = sqrq;
	}

	@Column(name = "DLRQZZP", length = 32)
	public String getDlrqzzp() {
		return this.dlrqzzp;
	}

	public void setDlrqzzp(String dlrqzzp) {
		this.dlrqzzp = dlrqzzp;
	}

	@Column(name = "JXMC")
	public String getJxmc() {
		return this.jxmc;
	}

	public void setJxmc(String jxmc) {
		this.jxmc = jxmc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CJSJ", length = 7)
	public Date getCjsj() {
		return this.cjsj;
	}

	public void setCjsj(Date cjsj) {
		this.cjsj = cjsj;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "GXSJ", length = 7)
	public Date getGxsj() {
		return this.gxsj;
	}

	public void setGxsj(Date gxsj) {
		this.gxsj = gxsj;
	}

	@Column(name = "CJYH", length = 20)
	public String getCjyh() {
		return this.cjyh;
	}

	public void setCjyh(String cjyh) {
		this.cjyh = cjyh;
	}

	@Column(name = "GXYH", length = 20)
	public String getGxyh() {
		return this.gxyh;
	}

	public void setGxyh(String gxyh) {
		this.gxyh = gxyh;
	}

	@Column(name = "ZKZMBH", length = 12)
	public String getZkzmbh() {
		return this.zkzmbh;
	}

	public void setZkzmbh(String zkzmbh) {
		this.zkzmbh = zkzmbh;
	}

	@Column(name = "CSBJ", length = 1)
	public Character getCsbj() {
		return this.csbj;
	}

	public void setCsbj(Character csbj) {
		this.csbj = csbj;
	}

}
