package com.xs.dzyxh.entity.driimg;

import java.sql.Blob;
import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * DrivingPhoto generated by hbm2java 驾驶人图片表
 */
@Entity
@Table(name = "TM_DRIVING_PHOTO", schema = "ARC_DRIVER_IMG")
public class DrivingPhoto implements java.io.Serializable {
	private String id;// 主键
	private String sfzmhm;// 身份证明号码
	private String lsh;// 流水号
	private byte[] zp;// 照片
	private String zpzl;// 照片类型
	private Date cjsj;// 创建时间
	private Date gxsj;// 更新时间
	private String cjyh;// 创建用户
	private String gxyh;// 更新用户
	private String jyw;// 校验位
	private String csbj;// 传输标记， 是否交换到公安网
	private String qh;// 期号
	private String jxdm;// 驾校代码,代码表外键

	public DrivingPhoto() {
	}

	public DrivingPhoto(String id, String sfzmhm, String lsh, byte[] zp, String zpzl, Date cjsj, Date gxsj, String cjyh,
			String gxyh, String jyw, String csbj,String qh,String jxdm) {
		this.id = id;
		this.sfzmhm = sfzmhm;
		this.lsh = lsh;
		this.zp = zp;
		this.zpzl = zpzl;
		this.cjsj = cjsj;
		this.gxsj = gxsj;
		this.cjyh = cjyh;
		this.gxyh = gxyh;
		this.jyw = jyw;
		this.csbj = csbj;
		this.qh=qh;
		this.jxdm=jxdm;
	}

	@Id
	@GenericGenerator(name = "uuid", strategy = "uuid")
	@GeneratedValue(generator = "uuid")
	@Column(name = "id")
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "SFZMHM", length = 22)
	public String getSfzmhm() {
		return sfzmhm;
	}

	public void setSfzmhm(String sfzmhm) {
		this.sfzmhm = sfzmhm;
	}

	@Column(name = "LSH", length = 32)
	public String getLsh() {
		return lsh;
	}

	public void setLsh(String lsh) {
		this.lsh = lsh;
	}

	@Lob
	@Basic(fetch = FetchType.LAZY)
	@Column(name = "ZP", columnDefinition = "BLOB", nullable = true)
	public byte[] getZp() {
		return zp;
	}

	public void setZp(byte[] zp) {
		this.zp = zp;
	}

	@Column(name = "ZPZL", length = 4)
	public String getZpzl() {
		return zpzl;
	}

	public void setZpzl(String zpzl) {
		this.zpzl = zpzl;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CJSJ", length = 7)
	public Date getCjsj() {
		return cjsj;
	}

	public void setCjsj(Date cjsj) {
		this.cjsj = cjsj;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "GXSJ", length = 7)
	public Date getGxsj() {
		return gxsj;
	}

	public void setGxsj(Date gxsj) {
		this.gxsj = gxsj;
	}

	@Column(name = "CJYH", length = 20)
	public String getCjyh() {
		return cjyh;
	}

	public void setCjyh(String cjyh) {
		this.cjyh = cjyh;
	}

	@Column(name = "GXYH", length = 20)
	public String getGxyh() {
		return gxyh;
	}

	public void setGxyh(String gxyh) {
		this.gxyh = gxyh;
	}

	@Column(name = "JYW", length = 255)
	public String getJyw() {
		return jyw;
	}

	public void setJyw(String jyw) {
		this.jyw = jyw;
	}

	@Column(name = "CSBJ", length = 2)
	public String getCsbj() {
		return csbj;
	}

	public void setCsbj(String csbj) {
		this.csbj = csbj;
	}

	@Column(name = "QH", length = 10)
	public String getQh() {
		if (qh == null) {
			return "";
		}
		return qh;
	}

	public void setQh(String qh) {
		this.qh = qh;
	}

	@Column(name = "JXDM", length = 2)
	public String getJxdm() {
		if (jxdm == null) {
			return "";
		}
		return jxdm;
	}

	public void setJxdm(String jxdm) {
		this.jxdm = jxdm;
	}

}
